theme: jekyll-theme-slate
title: Kerry Turner
description: Programmer, game maker, writer/n[Github](https://github.com/reallyfancy) [LinkedIn](https://www.linkedin.com/in/kerryturner) [Itch](https://reallyfancy.itch.io/) [Twitter](https://twitter.com/reallyfancy)
